spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fine_database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

# RDS 연결 정보
#    url: jdbc:mysql://fine.cwvwlhmmtlyg.us-east-1.rds.amazonaws.com:3306/fine_database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: admin
#    password: d4a1b2c3!

#다해 : mysql 연결이 계속 실패해서 일단 있던 db 연결해 둔 것 삭제 X
#spring:
 # datasource:
  #  url: jdbc:h2:tcp://localhost/~/jpashop
   # username: sa
    #password:
    #driver-class-name: org.h2.Driver

  jackson:
    serialization:
      fail-on-empty-beans: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace